### ISSUE TITLE
Encoding special chars with URL encoding

### ISSUE THREAD

**Issue by mrix** [libgraviton/php-rql-parser#37]
Lexer ignores rules written in [RQL documentation](https://github.com/persvr/rql#rql-rules):

> The RQL grammar is based around standard URI delimiters. The standard rules for encoding strings with URL encoding (%xx) are observed.

For example RQL `eq(id,a%20b)` is parsed as:

```
Graviton\Rql\AST\EqOperation {
  -property: "id"
  -value: "a%20b"
}
```

Expected result:

```
Graviton\Rql\AST\EqOperation {
  -property: "id"
  -value: "a b"
}
```

**Comment by narcoticfresh** [comment]
@hairmare This issue arised when I've seen some clients sending an RQL expression where the "value" part of the eq() was urlencoded() twice.. and I first thought it's a client side mistake..

Thinking about it, it makes sense.. sending the value urlencoded() by itself (so twice looking at the whole string), this allows the user to use all special characters (like , ( ) / and so on) inside the eq() value.. Agree?

**Comment by hairmare** [comment]
@narcoticfresh Yes, we don't support the correct way to `urlencode()`. I'm not sure what you mean by urlencoding twice, that sounds rather silly to me and it's not like we'll need it to support the bug described by this issue.

**Comment by narcoticfresh** [comment]
@hairmare Well, yes, my first feeling was also it's silly.. but consider the following..

User wants search `eq()` for a the value `value(with)special)`. 
Now, normal urlencode() would be: `eq%28field%2Cvalue%28with%29special%29`.

If we urldecode() this normally, we would think "value(with)" is something special, part of RQL expression. At least most parsers would, not sure about ours.

I think that's why the RQL spec recommends to urlencode() search val before as `value%28with%29special`, then put it like that in the whole construct, urlencode() again the whole to pass it via GET.. so it would become:
`eq%28field%2Cvalue%2528with%2529special%29`

+1 we should accept it.. We just need to urldecode() once more - and the problem of special character escaping would be solved according to the spec..(?)

**Comment by hairmare** [comment]
Done by switching to https://github.com/xiag-ag/rql-parser...

Thanks again @mrix
